# -*- coding: utf-8 -*-
"""PowerBI_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_yY2LMiyB63DHhkWjZ58d5jS5Pxnail
"""

!pip install xlsxwriter

import polars as pl
import xlsxwriter
import pandas as pd

boletim = pl.read_csv('boletim.csv', separator=';')
display(boletim.head(6))

boletim = boletim.with_columns(
    (pl.col('nota1') + pl.col('nota2') + pl.col('nota3') + pl.col('nota4')).alias('Total'),
    (pl.col('Total') / 4).alias('Média')
)
display(boletim.head(6))

boletim = boletim.with_columns(
    pl.when(pl.col('Média') >= 7)
    .then(pl.lit('Aprovado'))
    .otherwise(pl.lit('Reprovado'))
    .alias('Situação')
)
display(boletim.head(6))

# Use pl.write_excel to export to Excel
boletim.write_excel('boletim.xlsx', include_header=True)

vendas = pd.read_csv('baseaula2.csv', separator=';')
print(vendas.columns)

# Converter Data da Coleta para date
vendas['Data_Pedido'] = pd.to_datetime(vendas['Data_Pedido'], format='%d/%m/%Y')

#Converter valoor de venda para float
vendas['Valor de Venda'] = vendas['Valor de Venda'].str.replace(',', '.').astype(float)

display(vendas.head(51291))

#Pergunta 1 - Qual o valor total vendido?